apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: pravega-hello
spec:
  clusterServiceClassExternalName: keycloak-client
  clusterServicePlanExternalName: service-account
  parameters:
    client-id: pravega-hello
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: pravega-hello
spec:
  instanceRef:
    name: pravega-hello